### ISSUE TITLE
bibxml serializer: update anchor formatting logic for Internet Drafts

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton-py#10]
See also https://github.com/ietf-ribose/bibxml-service/issues/206.

Previously, we’d assume Relaton data provides a `docid` with `scope=anchor` property, and the corresponding `docid.id` value was used for `anchor` attribute on `<reference>` and `<referencegroup>` elements.

Now, because it doesn’t represent a general bibliographic item property and is considered relevant for xml2rfc, @ronaldtse made the call that `docid` with `scope=anchor` will be removed from source data, and  instead of using it serialization logic should take care of formatting the anchor based on primary docid.

**Comment by stefanomunarini** [comment]
Can we close this @strogonoff ?
