### ISSUE TITLE
`bibxml` serializer: need to convert `<jats:p>` to paragraphs

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton-py#12]
> We also have to normalise the `<jats:p>` element to the BibXML format. Right now there is already `<t>` for paragraphs but need to remove the `<jats:p>`.

```xml
<abstract>
  <t><jats:p>The fourth industrial revolution heralds a paradigm shift in how people...</jats:p></t>
</abstract>
```

NOTE: Seems that `<jats:p>` is encoded as text now.

_Originally posted by @ronaldtse in https://github.com/ietf-ribose/bibxml-service/issues/208#issuecomment-1136917042_

**Comment by strogonoff** [comment]
It may be better to create a set of paragraph extractors that is tied to abstract’s `format`, rather than trying to be smart and extract tags “if they occur” like it’s done now.

**Comment by ronaldtse** [comment]
Agreed.

**Comment by strogonoff** [comment]
Fixed in https://github.com/relaton/relaton-py/commit/9d9f978a59af0d31720967b3f2b2bb39cabf4b17, https://github.com/relaton/relaton-py/commit/ad5a8c9c97d6afb2e1244079648b9d647dadbdcf, https://github.com/relaton/relaton-py/commit/91c1cc09370910d0e6f85577f43d6d75c0c524d1.

@stefanomunarini maybe you could help adding a test for JATS paragraph extraction? See Ronald’s comment for a DOI specimen that has `<jats:p>` tags in it…

**Comment by strogonoff** [comment]
@stefanomunarini feel free to close when you consider it finished…
