### ISSUE TITLE
XML Schema validation fails after adding <refcontent> under <reference> element

### ISSUE THREAD

**Issue by stefanomunarini** [relaton/relaton-py#35]
After updating the reference serializer ([PR](https://github.com/relaton/relaton-py/pull/26))  to include **\<refcontent\>** as part of the **\<reference\>** element, the XML outputted stopped validating against the official [RNC Schema](https://github.com/ietf-tools/xml2rfc/blob/main/xml2rfc/data/v3.rnc).

As a reference, the error raised by the validator is:

```
lxml.etree.DocumentInvalid: Element 'reference', attribute 'refcontent': The attribute 'refcontent' is not allowed.
```

Related: https://github.com/ietf-ribose/bibxml-service/issues/155

**Comment by ronaldtse** [comment]
This is directly related to the comment made here:
https://github.com/ietf-ribose/bibxml-service/issues/228#issuecomment-1177699864

According to the latest RFCXML v3, `<refcontent>` is allowed in `<reference>`:
https://authors.ietf.org/rfcxml-vocabulary#refcontent

In addition, the RNC Schema supports `<refcontent>` in `<reference>`:
* https://github.com/ietf-tools/xml2rfc/blob/3d7e63462ea05b24c1a0d85a8edf1c4d9b8b4a3a/xml2rfc/data/v3.rnc#L1052-L1065
* https://github.com/ietf-tools/xml2rfc/blob/3d7e63462ea05b24c1a0d85a8edf1c4d9b8b4a3a/xml2rfc/data/v3.rnc#L1125-L1130

It seems that this is an instance of the validation process being broken?

**Comment by stefanomunarini** [comment]
> It seems that this is an instance of the validation process being broken?

What do you mean with this @ronaldtse ?

**Comment by ronaldtse** [comment]
The refcontent element is a valid one under reference, so validation failure should not happen. If it fails, it means the validation is broken?

**Comment by strogonoff** [comment]
@ronaldtse  I think the implication here is that RNC schema given to us to validate against may be wrong. The error is pretty clear: the schema we have, contrary to the comment that prompted us to use `<refcontent>`, does _not_ allow `<refcontent>`. Perhaps IETF has a more up-to-date schema?

**Comment by strogonoff** [comment]
@stefanomunarini or maybe we are using an outdated schema in tests?

**Comment by strogonoff** [comment]
@stefanomunarini  There could also be a potential where there were issues during the conversion of RNC to XSD, maybe this is what @ronaldtse meant.

Our XSD schema—I think it’s a result of semi-automatic RNC conversion—has `refcontent` here: https://github.com/relaton/relaton-py/blob/e44562f1b43268369ff973b197117e613f130a8e/relaton/tests/static/schemas/v3.xsd#L1362-L1373

Why does it fail? It looks like it allows an unbounded number of `refcontent` elements…

**Comment by strogonoff** [comment]
I think converting this:

https://github.com/ietf-tools/xml2rfc/blob/3d7e63462ea05b24c1a0d85a8edf1c4d9b8b4a3a/xml2rfc/data/v3.rnc#L1064

into this:

https://github.com/relaton/relaton-py/blob/e44562f1b43268369ff973b197117e613f130a8e/relaton/tests/static/schemas/v3.xsd#L1367-L1372

might be the source of this error.

`(foo | bar)*` in RNC does not mean only foo OR bar, but `xs:choice` seems to imply that.

**Comment by stefanomunarini** [comment]
It was indeed an instance of the validation process. This commit fixes it: https://github.com/relaton/relaton-py/pull/33/commits/eaf8273efa642d7c67cd3b61c8f56e7922f6312f

**Comment by ronaldtse** [comment]
Thanks @stefanomunarini !
