### ISSUE TITLE
Remove <xml ..> preamble

### ISSUE THREAD

**Issue by stefanomunarini** [relaton/relaton-py#43]

**Comment by stefanomunarini** [comment]
https://github.com/ietf-tools/bibxml-service/issues/275

**Comment by stefanomunarini** [comment]
Awaiting https://github.com/ietf-tools/bibxml-service/pull/279 to be merged by IETF maintainers

**Comment by ronaldtse** [comment]
@stefanomunarini let's close this then if we are just waiting for https://github.com/ietf-tools/bibxml-service/pull/279 to be merged?
