### ISSUE TITLE
Tests failing due to keyword format change in source data

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton-py#46]
By the way, if we are fetching Relaton YAML anew on each test run this may not be a good idea. This means relaton-py tests are also implicitly testing the correctness of data sources. Broken data sources should not fail relaton-py tests. The more correct way is to incorporate static test fixtures, and make sure they are updated whenever with format version updates.

**Comment by strogonoff** [comment]
Related: #45

**Comment by ronaldtse** [comment]
Agree with @strogonoff fully.

**Comment by stefanomunarini** [comment]
Agree with that, however having tests to validate data sources also helps with identifying which data has changed given that there seems to be no notification of this kind of updates.

**Comment by stefanomunarini** [comment]
I will use this issue to report the discrepancy with the new data format:

- [IANA](https://raw.githubusercontent.com/ietf-tools/relaton-data-iana/main/data/bgp-extended-communities_arp-nd-extended-community-flags.yaml): 
```
contributor -> 0 -> organization -> abbreviation
  str type expected (type=type_error.str)
```
- [IEEE](https://raw.githubusercontent.com/ietf-tools/relaton-data-ieee/main/data/ANSI_IEEE_991-1986.yaml): 
```
contributor -> 0 -> organization -> abbreviation
  str type expected (type=type_error.str)
keyword
  str type expected (type=type_error.str)
keyword -> 0
  str type expected (type=type_error.str)
copyright -> 0 -> owner -> 0 -> name -> 0
  str type expected (type=type_error.str)
copyright -> 0 -> owner -> 0 -> name
  str type expected (type=type_error.str)
copyright -> 0 -> owner -> 0 -> abbreviation
  str type expected (type=type_error.str)
copyright -> from
  field required (type=value_error.missing)
copyright -> owner
  value is not a valid list (type=type_error.list)
```

- [ID](https://raw.githubusercontent.com/ietf-tools/relaton-data-ids/main/data/draft-ayers-low-power-interop-02.yaml): 
```
contributor -> 0 -> person -> name -> given -> forename -> 0
  Forename.__init__() missing 1 required positional argument: 'content' (type=type_error)
contributor -> 0 -> person -> name -> given -> forename -> content
  str type expected (type=type_error.str)
```

- [MISC](https://raw.githubusercontent.com/ietf-tools/relaton-data-misc/main/data/reference.W3C.soap11.yaml): 
```
contributor -> 0 -> person -> name -> given -> forename -> 0
  Forename.__init__() missing 1 required positional argument: 'content' (type=type_error)
contributor -> 0 -> person -> name -> given -> forename -> content
  str type expected (type=type_error.str)
```

- [NIST](https://raw.githubusercontent.com/ietf-tools/relaton-data-nist/main/data/NBS_BH_1.yaml): 
```
contributor -> 8 -> organization -> abbreviation
  str type expected (type=type_error.str)
```

- [RFCS](https://raw.githubusercontent.com/ietf-tools/relaton-data-rfcs/main/data/RFC0001.yaml): 
```
contributor -> 0 -> person -> name -> given -> forename -> 0
  Forename.__init__() missing 1 required positional argument: 'content' (type=type_error)
contributor -> 0 -> person -> name -> given -> forename -> content
  str type expected (type=type_error.str)
```

As discussed with @strogonoff I could work on normalising this data on bibxml-service; however, as this discrepancy only regard specific datasets, wouldn't it be better to fix it at source data level? Most of the errors are due to using a LocalisedString instead of a simple string. For consistency, I'd say it will be better to have all the datasets data normalized at the source.

**Comment by strogonoff** [comment]
As an update after our chat and more thinking, I suppose the workflow should be:

- De-facto *Relaton schema version* is the same as *`relaton-cli` version* (currently 1.13); every time schema is updated a new minor version comes out.
  - So, 1.13 is our current schema version, and 1.14 will be a different Relaton YAML structure
- Test fixtures with YAML of all supported schema versions should be included as part of the repository (not fetched from external sources)
  - There can be multiple fixture groups, one for each supported schema version, and we can test against all
  - When schema is updated, we add test fixtures for that version
  - `relaton-py` is more than just schema support, so we have to maintain parallel version branches and backport some non-schema-related changes (e.g., security fixes, if any) to `relaton-py` versions that support older Relaton schema versions.
    - Similar to how projects like Django handle it: after 4.x is released, 3.x may not get major new features but will receive security fixes and minor versions will still come out.
- We should document Relaton schema version support matrix for `relaton-py`.
  - E.g., `relaton-py==0.2.20` supports schema 1.12 and 1.13, `relaton-py==0.3.0` supports 1.12, 1.13 and 1.14, etc.
  - We can decide on versioning rules and how to simplify this matrix, but we don’t necessarily have to.
  - We can also auto-generate the matrix based on which fixtures are tested in which version branch.

**Comment by strogonoff** [comment]
Note: per @opoudjis’s suggestion we may want to use numbers from https://github.com/relaton/relaton-models/releases as schema version numbers rather than Relaton gem versions. Hopefully @andrew2net can make those numbers appear in YAML.

**Comment by andrew2net** [comment]
> Hopefully @andrew2net can make those numbers appear in YAML.

Those numbers should appear in the grammar first. We use an XML format to save documents in the relaton cache, so
the numbers will be lost if we don't have an XML element to keep them.
CC @opoudjis.

**Comment by stefanomunarini** [comment]
@opoudjis any ETA on when relaton-data is going to be updated to include the new **schema-version** attribute?

**Comment by opoudjis** [comment]
.... @stefanomunarini I have no idea what you are referring to by relaton-data, and I don't think I can help you here. 

I have put the schema-version attribute in the grammar, a very long time ago. That is the full extent of my involvement in any of this; I don't do any relaton development. The next step is for @andrew2net to incorporate it into the relaton document model, if he hasn't already. Populating it automatically from the latest grammar update or gem version is also coding that I'm not involved in.

**Comment by andrew2net** [comment]
@strogonoff can we close this issue?
