### ISSUE TITLE
(URGENT) Support contributor.person.name.forename

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-py#49]
From https://github.com/ietf-tools/bibxml-service/issues/300:

While this has been merged:
* https://github.com/relaton/relaton-py/issues/39

The issue still exists:
https://bib.ietf.org/indexed-sources/relaton-data-nist/NISTIR_90-4250/

<img width="813" alt="Screen Shot 2022-10-11 at 5 54 23 PM" src="https://user-images.githubusercontent.com/11865/195058949-174a8b89-8ec2-45c9-ac02-59c9ca07e1bf.png">

**Comment by ronaldtse** [comment]
Actually perhaps the problem is that our fork has not been merged into the ietf-tools' repo...

<img width="530" alt="Screen Shot 2022-10-11 at 5 56 53 PM" src="https://user-images.githubusercontent.com/11865/195059534-82879cf6-77b8-4b47-942b-25dc3c7ef277.png">

**Comment by stefanomunarini** [comment]
@ronaldtse we will create a PR to ietf fork soon, @strogonoff is working on some other minor updates and we will include everything in the same PR.
